package uk.co.jamesj999.sonic.tools.disasm;

import java.io.IOException;
import java.io.Writer;
import java.util.Comparator;
import java.util.List;

/**
 * Exports verified ROM offsets as Java constants.
 */
public class ConstantsExporter {

    /**
     * Export verified results as Java constants to the given writer.
     *
     * @param results List of verification results to export
     * @param prefix  Optional prefix for constant names (e.g., "ART_")
     * @param writer  Output writer
     */
    public void exportAsJavaConstants(List<VerificationResult> results, String prefix, Writer writer)
            throws IOException {
        // Filter to verified only and sort by offset
        List<VerificationResult> verified = results.stream()
                .filter(r -> r.getStatus() == VerificationResult.Status.VERIFIED)
                .sorted(Comparator.comparing(VerificationResult::getCalculatedOffset))
                .toList();

        if (verified.isEmpty()) {
            writer.write("// No verified offsets to export\n");
            return;
        }

        writer.write("// Generated by RomOffsetFinder\n");
        writer.write("// Verified against Sonic 2 (REV01)\n\n");

        for (VerificationResult r : verified) {
            String constName = toConstantName(r.getLabel(), prefix);
            String typeName = r.getCompressionType() != null ? r.getCompressionType().getDisplayName() : "Unknown";

            writer.write(String.format("/** %s - %s compressed */%n", r.getLabel(), typeName));
            writer.write(String.format("public static final long %s_OFFSET = 0x%06X;%n",
                    constName, r.getCalculatedOffset()));
            writer.write(String.format("public static final int %s_SIZE = %d;%n",
                    constName, r.getFileSize()));
            writer.write("\n");
        }
    }

    /**
     * Convert a disassembly label to a Java constant name.
     * Examples:
     * - ArtNem_SpecialRings -> NEM_SPECIAL_RINGS
     * - ArtKos_SpecialStage -> KOS_SPECIAL_STAGE
     * - Pal_SS -> PAL_SS
     *
     * @param label  The original label
     * @param prefix Optional prefix to prepend
     * @return Java-style constant name
     */
    public String toConstantName(String label, String prefix) {
        String name = label;

        // Handle common prefixes from disassembly
        if (name.startsWith("ArtNem_")) {
            name = "NEM_" + name.substring(7);
        } else if (name.startsWith("ArtKos_")) {
            name = "KOS_" + name.substring(7);
        } else if (name.startsWith("ArtEni_")) {
            name = "ENI_" + name.substring(7);
        } else if (name.startsWith("ArtSax_")) {
            name = "SAX_" + name.substring(7);
        } else if (name.startsWith("Pal_")) {
            name = "PAL_" + name.substring(4);
        } else if (name.startsWith("MapEni_")) {
            name = "MAP_ENI_" + name.substring(7);
        } else if (name.startsWith("MapUnc_")) {
            name = "MAP_UNC_" + name.substring(7);
        }

        // Convert camelCase to UPPER_SNAKE_CASE
        StringBuilder result = new StringBuilder();
        for (int i = 0; i < name.length(); i++) {
            char c = name.charAt(i);
            if (Character.isUpperCase(c) && i > 0) {
                char prev = name.charAt(i - 1);
                // Add underscore before uppercase if preceded by lowercase
                if (Character.isLowerCase(prev)) {
                    result.append('_');
                }
            }
            result.append(Character.toUpperCase(c));
        }

        // Apply prefix if provided
        if (prefix != null && !prefix.isEmpty()) {
            return prefix + result.toString();
        }
        return result.toString();
    }

    /**
     * Suggest which constants file should receive the exported constants.
     *
     * @param label The label to check
     * @return Suggested filename
     */
    public String suggestConstantsFile(String label) {
        if (label.contains("Special") || label.contains("SS")) {
            return "Sonic2SpecialStageConstants.java";
        }
        return "Sonic2Constants.java";
    }
}
