package com.openggf.trace.replay.runs;

import com.openggf.debug.playback.Bk2FrameInput;
import com.openggf.game.GameServices;
import com.openggf.game.resources.DynamicArtDiagnosticsSnapshot;
import com.openggf.game.resources.QueueDiagnosticSnapshot;
import com.openggf.game.timing.HardwareTimingSnapshot;
import com.openggf.sprites.playable.AbstractPlayableSprite;
import com.openggf.trace.FieldComparison;
import com.openggf.trace.FrameComparison;
import com.openggf.trace.LoadQueueComparisonProjection;
import com.openggf.trace.Severity;
import com.openggf.trace.ToleranceConfig;
import com.openggf.trace.TraceBinder;
import com.openggf.trace.TraceData;
import com.openggf.trace.TraceFrame;
import com.openggf.trace.TraceHudModel;
import com.openggf.trace.live.MismatchEntry;

import java.util.ArrayDeque;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.Supplier;

/**
 * Compares run rows produced while native presentation owns the game loop.
 *
 * <p>Presentation rows deliberately have no playable-state comparison. Their
 * replay contract is limited to the physical BK2 input, production load
 * queues, and dynamic-art publication generated by that same logical row.
 */
public final class TraceStructuralRowComparator implements TraceHudModel {
    private final TraceData trace;
    private final TraceBinder binder;
    private final Supplier<List<QueueDiagnosticSnapshot>> queueSnapshots;
    private final Supplier<HardwareTimingSnapshot> hardwareTiming;

    private int cursor;
    private Bk2FrameInput preparedInput;
    private TraceFrame deferredTerminalFrame;
    private FrameComparison deferredTerminalBase;
    private DynamicArtDiagnosticsSnapshot deferredTerminalBaseline;
    private boolean terminalFinalized;
    private int errorCount;
    private int warningCount;
    private int laggedFrames;
    private int recentActionMask;
    private int recentInputMask;
    private boolean recentStartPressed;
    private final ArrayDeque<MismatchEntry> recentMismatches =
            new ArrayDeque<>();

    public TraceStructuralRowComparator(
            TraceData trace,
            ToleranceConfig tolerances,
            int initialCursor) {
        this(trace, tolerances, initialCursor,
                GameServices::captureQueueDiagnostics,
                () -> GameServices.hardwareTiming().capture());
    }

    public TraceStructuralRowComparator(
            TraceData trace,
            ToleranceConfig tolerances,
            int initialCursor,
            Supplier<List<QueueDiagnosticSnapshot>> queueSnapshots) {
        this(trace, tolerances, initialCursor, queueSnapshots,
                () -> GameServices.hardwareTiming().capture());
    }

    public TraceStructuralRowComparator(
            TraceData trace,
            ToleranceConfig tolerances,
            int initialCursor,
            Supplier<List<QueueDiagnosticSnapshot>> queueSnapshots,
            Supplier<HardwareTimingSnapshot> hardwareTiming) {
        this.trace = Objects.requireNonNull(trace, "trace");
        this.binder = new TraceBinder(
                Objects.requireNonNull(tolerances, "tolerances"));
        if (initialCursor < 0 || initialCursor > trace.frameCount()) {
            throw new IllegalArgumentException(
                    "initialCursor outside trace row range");
        }
        this.cursor = initialCursor;
        this.queueSnapshots = Objects.requireNonNull(
                queueSnapshots, "queueSnapshots");
        this.hardwareTiming = Objects.requireNonNull(
                hardwareTiming, "hardwareTiming");
    }

    /** Selects the exact physical BK2 frame represented by the next row. */
    public void prepareRow(Bk2FrameInput physicalInput) {
        Objects.requireNonNull(physicalInput, "physicalInput");
        if (preparedInput != null) {
            throw new IllegalStateException(
                    "structural comparison row is already prepared");
        }
        if (deferredTerminalFrame != null) {
            throw new IllegalStateException(
                    "terminal structural row is awaiting segment closure");
        }
        if (cursor >= trace.frameCount()) {
            throw new IllegalStateException(
                    "structural comparison has no remaining rows");
        }
        preparedInput = physicalInput;
        recentActionMask = physicalInput.p1ActionMask();
        recentInputMask = physicalInput.p1InputMask();
        recentStartPressed = physicalInput.p1StartPressed();
    }

    /**
     * Completes one represented production row after its PLC lifecycle closes.
     *
     * <p>The terminal row retains its input and queue result here, but returns
     * no comparison until {@link #finalizeSegment(DynamicArtDiagnosticsSnapshot)}
     * can append the dynamic-art state published by comparison-window closure.
     */
    public FrameComparison completePostProduction(
            DynamicArtDiagnosticsSnapshot before,
            DynamicArtDiagnosticsSnapshot after) {
        return completePostProduction(before, after, true, false);
    }

    public FrameComparison completePostProduction(
            DynamicArtDiagnosticsSnapshot before,
            DynamicArtDiagnosticsSnapshot after,
            boolean publicationRequired) {
        return completePostProduction(
                before, after, publicationRequired, false);
    }

    public FrameComparison completePostProduction(
            DynamicArtDiagnosticsSnapshot before,
            DynamicArtDiagnosticsSnapshot after,
            boolean publicationRequired,
            boolean lagged) {
        if (preparedInput == null) {
            throw new IllegalStateException(
                    "structural comparison row was not prepared");
        }
        TraceFrame expected = trace.getFrame(cursor);
        FrameComparison base = compareInputAndQueues(expected, preparedInput);
        boolean terminal = cursor == trace.frameCount() - 1;
        preparedInput = null;
        cursor++;
        if (lagged) {
            laggedFrames++;
        }

        if (!trace.metadata().hasPerFrameDynamicArtTransferState()) {
            terminalFinalized = terminal;
            return absorb(base);
        }
        Objects.requireNonNull(before, "before");
        Objects.requireNonNull(after, "after");
        if (terminal) {
            deferredTerminalFrame = expected;
            deferredTerminalBase = base;
            deferredTerminalBaseline = after;
            return null;
        }

        if (publicationRequired) {
            requireAtomicPublication(expected, before, after);
        } else if (!after.equals(before)) {
            throw new IllegalStateException(
                    "input-only structural row changed dynamic-art publication");
        }
        FrameComparison dynamic = binder.compareDynamicArt(
                trace.dynamicArtTransferStateForFrame(expected.frame()), after);
        return absorb(merge(base, dynamic));
    }

    /**
     * Appends the terminal dynamic-art heartbeat after the segment comparison
     * window has closed. Repeated calls after publication are no-ops.
     */
    public FrameComparison finalizeSegment(
            DynamicArtDiagnosticsSnapshot afterClosureSnapshot) {
        if (preparedInput != null) {
            throw new IllegalStateException(
                    "cannot finalize with a prepared structural row");
        }
        if (terminalFinalized) {
            return null;
        }
        if (deferredTerminalFrame == null) {
            throw new IllegalStateException(
                    "terminal structural row has not completed production");
        }
        DynamicArtDiagnosticsSnapshot actual = Objects.requireNonNull(
                afterClosureSnapshot, "afterClosureSnapshot");
        requireTerminalPublication(
                deferredTerminalFrame, deferredTerminalBaseline, actual);
        FrameComparison dynamic = binder.compareDynamicArt(
                trace.dynamicArtTransferStateForFrame(
                        deferredTerminalFrame.frame()),
                actual);
        FrameComparison result = absorb(merge(deferredTerminalBase, dynamic));
        deferredTerminalFrame = null;
        deferredTerminalBase = null;
        deferredTerminalBaseline = null;
        terminalFinalized = true;
        return result;
    }

    public int cursor() {
        return cursor;
    }

    public boolean isComplete() {
        return cursor >= trace.frameCount()
                && preparedInput == null
                && deferredTerminalFrame == null;
    }

    /** True after the coordinator may close the segment's terminal window. */
    public boolean allRowsConsumed() {
        return cursor >= trace.frameCount() && preparedInput == null;
    }

    @Override
    public int errorCount() {
        return errorCount;
    }

    @Override
    public int warningCount() {
        return warningCount;
    }

    @Override
    public int laggedFrames() {
        return laggedFrames;
    }

    @Override
    public int recentActionMask() {
        return recentActionMask;
    }

    @Override
    public int recentInputMask() {
        return recentInputMask;
    }

    @Override
    public boolean recentStartPressed() {
        return recentStartPressed;
    }

    @Override
    public List<MismatchEntry> recentMismatches() {
        return List.copyOf(recentMismatches);
    }

    @Override
    public boolean hasRecordingDesync() {
        return errorCount > 0;
    }

    private FrameComparison absorb(FrameComparison result) {
        for (FieldComparison field : result.fields().values()) {
            if (field.severity() == Severity.ERROR) {
                errorCount++;
            } else if (field.severity() == Severity.WARNING) {
                warningCount++;
            }
            if (field.isDivergent()) {
                if (recentMismatches.size() == 5) {
                    recentMismatches.removeFirst();
                }
                recentMismatches.addLast(new MismatchEntry(
                        result.frame(), field.fieldName(), field.expected(),
                        field.actual(), String.valueOf(field.delta()),
                        field.severity(), 1));
            }
        }
        return result;
    }

    private FrameComparison compareInputAndQueues(
            TraceFrame expected, Bk2FrameInput physicalInput) {
        FrameComparison result = new FrameComparison(
                expected.frame(), Map.of());
        if (trace.metadata().hasPerFrameLoadQueueState()) {
            LoadQueueComparisonProjection projection =
                    LoadQueueComparisonProjection.project(
                            trace,
                            expected.frame(),
                            trace.loadQueueStatesForComparisonFrame(expected.frame()),
                            queueSnapshots.get(),
                            hardwareTiming.get());
            binder.compareLoadQueues(
                    expected.frame(), projection.expected(), projection.actual());
            result = Objects.requireNonNull(
                    binder.comparisonForFrame(expected.frame()),
                    "queue comparison");
        }
        int actualInput = physicalInput.p1InputMask();
        if (physicalInput.p1ActionMask() != 0) {
            actualInput |= AbstractPlayableSprite.INPUT_JUMP;
        }
        if (binder.validateInput(expected, actualInput)) {
            return result;
        }
        LinkedHashMap<String, FieldComparison> fields =
                new LinkedHashMap<>(result.fields());
        fields.put("input_alignment", new FieldComparison(
                "input_alignment",
                String.format("0x%04X", expected.input() & 0xFFFF),
                String.format("0x%04X", actualInput & 0xFFFF),
                Severity.ERROR,
                Math.abs((expected.input() & 0xFFFF) - actualInput)));
        return new FrameComparison(
                expected.frame(), fields,
                result.romDiagnostics(), result.engineDiagnostics());
    }

    private static void requireAtomicPublication(
            TraceFrame expected,
            DynamicArtDiagnosticsSnapshot before,
            DynamicArtDiagnosticsSnapshot after) {
        if (after.deliverySerial() <= before.deliverySerial()
                || !after.published()
                || after.segmentGeneration() != before.segmentGeneration()
                || after.frame() != expected.frame()) {
            throw new IllegalStateException(
                    "dynamic-art row " + expected.frame()
                            + " was not published atomically after production");
        }
    }

    private static void requireTerminalPublication(
            TraceFrame expected,
            DynamicArtDiagnosticsSnapshot beforeClosure,
            DynamicArtDiagnosticsSnapshot afterClosure) {
        if (afterClosure.deliverySerial() < beforeClosure.deliverySerial()
                || !afterClosure.published()
                || afterClosure.segmentGeneration()
                        != beforeClosure.segmentGeneration()
                || afterClosure.frame() != expected.frame()) {
            throw new IllegalStateException(
                    "dynamic-art terminal row " + expected.frame()
                            + " was not available after segment closure");
        }
    }

    private static FrameComparison merge(
            FrameComparison base, FrameComparison addition) {
        LinkedHashMap<String, FieldComparison> fields =
                new LinkedHashMap<>(base.fields());
        fields.putAll(addition.fields());
        return new FrameComparison(
                base.frame(), fields,
                base.romDiagnostics().isEmpty()
                        ? addition.romDiagnostics() : base.romDiagnostics(),
                base.engineDiagnostics().isEmpty()
                        ? addition.engineDiagnostics() : base.engineDiagnostics());
    }
}
