package com.openggf.audio.synth.nuked;

import org.junit.jupiter.api.Test;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.MethodHandles;
import java.lang.invoke.MethodType;

import static org.junit.jupiter.api.Assertions.assertEquals;

/**
 * Independent fingerprints from the pinned C OPN2_PhaseCalcIncrement, generated by
 * tools/audio/nuked-opn2/harness/phase-matrix-harness.c. These isolate arithmetic;
 * TestNukedOpn2BitExactScripts covers integration with the cycle pipeline.
 */
class TestNukedOpn2PhaseMatrix {
    private static final long OFFSET = 0xcbf29ce484222325L;
    private static final MethodHandle PHASE = phaseMethod();

    @Test
    void zeroSensitivityMatchesReferenceForEveryFrequencyAndLfoPhase() throws Throwable {
        NukedOpn2 core = new NukedOpn2();
        long hash = OFFSET;
        for (int fnum = 0; fnum < 2048; fnum++) {
            for (int lfo = 0; lfo < 32; lfo++) {
                hash = phaseHash(core, hash, fnum, 7, 31, 0, 7, lfo, 30);
            }
        }
        assertEquals(0x88bfe960c6f67325L, hash, "65,536 zero-PMS reference cases");
    }

    @Test
    void everySignedDetuneAndKeycodeMatchesReference() throws Throwable {
        NukedOpn2 core = new NukedOpn2();
        long hash = OFFSET;
        for (int dt = 0; dt < 8; dt++) {
            for (int code = 0; code < 32; code++) {
                hash = phaseHash(core, hash, 1024, 3, code, 0, dt, 0, 2);
            }
        }
        assertEquals(0x59778aea1488df65L, hash, "256 signed-detune reference cases");
    }

    @Test
    void activeModulationMatchesReferenceAcrossArithmeticBoundaries() throws Throwable {
        NukedOpn2 core = new NukedOpn2();
        int[] frequencies = {0, 1, 15, 16, 127, 128, 1023, 2047};
        int[] blocks = {0, 3, 7};
        int[] codes = {0, 15, 28, 31};
        // Internal MULTI is 1 for register zero, otherwise twice the register.
        // Include its upper range and two extra arithmetic-only inputs (0, 15).
        int[] multiples = {0, 1, 2, 15, 16, 30};
        long hash = OFFSET;
        for (int pms = 1; pms < 8; pms++) {
            for (int lfo = 0; lfo < 32; lfo++) {
                for (int fnum : frequencies) {
                    for (int block : blocks) {
                        for (int dt = 0; dt < 8; dt++) {
                            for (int code : codes) {
                                for (int multi : multiples) {
                                    hash = phaseHash(core, hash, fnum, block, code, pms, dt, lfo, multi);
                                }
                            }
                        }
                    }
                }
            }
        }
        assertEquals(0xea93f3fc6c934311L, hash, "1,032,192 active-PMS reference cases");
    }

    private static long phaseHash(NukedOpn2 core, long hash, int fnum, int block,
                                  int code, int pms, int dt, int lfo, int multi) throws Throwable {
        NukedOpn2State chip = core.state();
        chip.cycles = 3;
        chip.channel = 0;
        chip.pgFnum = fnum;
        chip.pgBlock = block;
        chip.pgKcode = code;
        chip.pms[0] = pms;
        chip.dt[3] = dt;
        chip.lfoPm = lfo;
        chip.multi[3] = multi;
        PHASE.invokeExact(core);
        int value = chip.pgInc[3];
        for (int shift = 0; shift < 32; shift += 8) {
            hash = (hash ^ ((value >>> shift) & 255)) * 0x100000001b3L;
        }
        return hash;
    }

    private static MethodHandle phaseMethod() {
        try {
            return MethodHandles.privateLookupIn(NukedOpn2.class, MethodHandles.lookup())
                    .findVirtual(NukedOpn2.class, "phaseCalcIncrement", MethodType.methodType(void.class));
        } catch (ReflectiveOperationException e) {
            throw new ExceptionInInitializerError(e);
        }
    }
}
