package com.openggf.tools.audio.parity.s2;

/** Fixed, unbound identities for the request-aware bounded S2 candidate. */
final class S2RequestAwareOracleSchema {
    public static final String PAYLOAD_SCHEMA = "openggf.s2-oracle-audio-raw.v2";
    public static final String SOURCE_SCHEMA = "openggf.s2-complete-run-audio-raw.v4";
    public static final String REQUEST_TRANSFER_SCHEMA =
            "openggf.s2-preconsumption-request-transfer.v2";
    public static final String S2_REV01_SHA1 = "8bca5dcef1af3e00098666fd892dc1c2a76333f9";
    public static final String BK2_SHA256 =
            "e850798f882b8c580aad148bc97cb50f260cae1d336dd649fe2f4dfae6796aa5";
    public static final String SERVICE_MANIFEST_SHA256 =
            "ef8f8103c38d70e41cb09cb29751f56815a0401709dc509071aa514d614813a0";
    public static final String INVENTORY_DIGEST_DOMAIN = "compact-json-lf-v1";
    public static final String BODY_DIGEST_DOMAIN = "bounded-jsonl-body-bytes-v1";
    public static final String TERMINAL_STATE_DIGEST_DOMAIN = "decoded-z80-state-bytes-v1";
    public static final String PAYLOAD_PREFIX_DIGEST_DOMAIN =
            "bounded-jsonl-before-cutoff-bytes-v1";
    public static final int FIRST_ROW = 10_150;
    public static final int EXCLUSIVE_END = 10_900;
    /**
     * The complete run's own bounds, kept as the recording's description
     * rather than as any window's source scope. A published window is cut
     * from a capture bounded to itself, so its source scope is its own.
     */
    public static final int SOURCE_FIRST_ROW = 769;
    public static final int SOURCE_EXCLUSIVE_END = 259_590;
    public static final int STATE_BYTES = 0x2000;
    public static final int REQUEST_PC = 0x10d6;
    /**
     * {@code sndDriverInput}'s other store into Z80 RAM: {@code move.b
     * d0,zVar.QueueToPlay(a1)} at {@code .isNotPauseCommand}, which the
     * disassembly labels {@code loc_10C0} (docs/s2disasm/s2.asm:1302-1304).
     * It carries every music request, and any sound a caller routes through
     * {@code PlayMusic} rather than {@code PlaySound}, such as the
     * ring-milestone check at :25913-25914.
     */
    public static final int MUSIC_REQUEST_PC = 0x10c0;
    /**
     * The slot a music transfer is recorded under. {@code D1} is a queue slot
     * only at {@link #REQUEST_PC}, where {@code .loop} sets it; at
     * {@link #MUSIC_REQUEST_PC} it holds the pause-check residue of
     * {@code move.b d0,d1} and {@code subi.b #MusID_Pause,d1} (:1294-1295).
     * Four is outside the driver's 0..3 SFX queue, so the two can never be
     * confused.
     */
    public static final int MUSIC_SLOT = 4;
    /** The fixed pre-execution instruction at {@link #REQUEST_PC}: move.b D0,$09(A1,D1.w). */
    public static final String REQUEST_OPCODE = "13801009";
    public static final int REQUEST_MARKER_TOKEN = 24;
    public static final int REQUEST_SERVICE_MARKER_TOKEN = 25;
    public static final int MAX_LINE_BYTES = 1 << 20;

    /**
     * One published bounded candidate: the recording it was cut from and the
     * exact movie rows it covers. Every field is an identity the strict reader
     * matches exactly, so widening to another interval or another recording
     * stays a pinned match rather than a relaxed one.
     */
    record Window(String name, String bk2Sha256, int firstRow, int exclusiveEnd,
            int sourceFirstRow, int sourceExclusiveEnd) {
        Window {
            if (firstRow < 0 || exclusiveEnd <= firstRow) {
                throw new IllegalArgumentException("window is not a valid interval");
            }
        }
    }

    /**
     * The originally published EHZ-reload window, and the default everywhere.
     *
     * <p>Its source scope is its own bounds. Every published window is now cut
     * from a capture bounded to that window rather than from one capture of
     * the whole run, so a window can be regenerated by itself.
     */
    // Keeps the complete run's source bounds because the full-capture entry
    // point still describes a window cut from one capture of the whole run.
    // The published payloads are read through the window-source entry instead:
    // each is now cut from a capture bounded to its own window, so a window can
    // be regenerated by itself.
    static final Window CONTROL = new Window("w10150-10900", BK2_SHA256,
            FIRST_ROW, EXCLUSIVE_END, SOURCE_FIRST_ROW, SOURCE_EXCLUSIVE_END);

    private S2RequestAwareOracleSchema() {
    }
}
