package com.openggf.graphics;

import org.joml.Matrix4f;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.Assumptions;
import org.junit.jupiter.api.Assumptions;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Assumptions;
import org.junit.jupiter.api.Test;
import org.lwjgl.glfw.GLFWErrorCallback;
import org.lwjgl.opengl.GL;
import com.openggf.Engine;
import com.openggf.camera.Camera;
import com.openggf.game.GameServices;
import com.openggf.tests.TestSessionOutputPaths;
import com.openggf.configuration.SonicConfiguration;
import com.openggf.configuration.SonicConfigurationService;
import com.openggf.data.Rom;
import com.openggf.game.GameModuleRegistry;
import com.openggf.level.LevelManager;
import com.openggf.level.ParallaxManager;
import com.openggf.sprites.managers.SpriteManager;
import com.openggf.sprites.playable.AbstractPlayableSprite;
import com.openggf.sprites.playable.Sonic;

import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

import static org.junit.jupiter.api.Assertions.*;
import static org.junit.jupiter.api.Assumptions.assumeTrue;
import static org.lwjgl.glfw.GLFW.*;
import static org.lwjgl.opengl.GL11.*;
import static org.lwjgl.system.MemoryUtil.NULL;
import static com.openggf.tests.RomTestUtils.ensureRomAvailable;

/**
 * Visual regression tests that compare rendered level screenshots against pre-generated reference images.
 * This ensures that rendering changes do not introduce visual regressions.
 *
 * Reference files are generated by VisualReferenceGenerator and stored in src/test/resources/visual-reference/
 *
 * Usage:
 * <pre>
 * # Generate reference images first
 * mvn exec:java -Dexec.mainClass="com.openggf.graphics.VisualReferenceGenerator" -q
 *
 * # Run visual regression tests
 * mvn test -Dtest=VisualRegressionTest
 * </pre>
 */
public class VisualRegressionTest {

    private static final String REFERENCE_DIR = "visual-reference";
    private static final int SCREEN_WIDTH = 320;
    private static final int SCREEN_HEIGHT = 224;

    // Tolerance for per-channel pixel comparison (allows minor GPU/driver variations)
    private static final int PIXEL_TOLERANCE = 5;

    private static long window;
    private static Rom rom;
    private static boolean referenceFilesExist;
    private static boolean initialized;
    private static boolean originalDebugViewEnabled;

    // JOML matrix for projection
    private static final Matrix4f projectionMatrix = new Matrix4f();
    private static final float[] matrixBuffer = new float[16];

    @BeforeAll
    public static void setUpClass() {
        try {
            // Save and disable debug view to avoid rendering debug markers (e.g., LayerSwitcher)
            originalDebugViewEnabled = SonicConfigurationService.getInstance()
                    .getBoolean(SonicConfiguration.DEBUG_VIEW_ENABLED);
            SonicConfigurationService.getInstance().setConfigValue(SonicConfiguration.DEBUG_VIEW_ENABLED, false);

            // Check if reference files exist first
            referenceFilesExist = referenceFileExists("ehz_a1_cp1.png");

            // Setup error callback
            GLFWErrorCallback.createPrint(System.err).set();

            // Initialize GLFW
            if (!glfwInit()) {
                throw new IllegalStateException("Unable to initialize GLFW");
            }

            // Configure GLFW for offscreen rendering
            glfwDefaultWindowHints();
            glfwWindowHint(GLFW_VISIBLE, GLFW_FALSE);
            glfwWindowHint(GLFW_RESIZABLE, GLFW_FALSE);
            glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 2);
            glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 1);

            // Create hidden window for offscreen rendering
            window = glfwCreateWindow(SCREEN_WIDTH, SCREEN_HEIGHT, "Visual Regression Test", NULL, NULL);
            if (window == NULL) {
                throw new RuntimeException("Failed to create GLFW window");
            }

            // Make context current
            glfwMakeContextCurrent(window);

            // Create GL capabilities
            GL.createCapabilities();

            // Initialize graphics manager with shader
            GraphicsManager graphicsManager = GraphicsManager.getInstance();
            graphicsManager.init(Engine.RESOURCES_SHADERS_PIXEL_SHADER_GLSL);

            // Set viewport
            glViewport(0, 0, SCREEN_WIDTH, SCREEN_HEIGHT);

            // Set up projection matrix using JOML
            glMatrixMode(GL_PROJECTION);
            glLoadIdentity();
            projectionMatrix.identity().ortho2D(0, SCREEN_WIDTH, 0, SCREEN_HEIGHT);
            projectionMatrix.get(matrixBuffer);
            glLoadMatrixf(matrixBuffer);

            // Provide projection matrix to GraphicsManager for shader-based rendering
            // (required since Engine.getInstance() returns null in test context)
            graphicsManager.setProjectionMatrixBuffer(matrixBuffer.clone());

            glMatrixMode(GL_MODELVIEW);
            glLoadIdentity();

            // Enable blending for transparency
            glEnable(GL_BLEND);
            glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);

            // Update viewport dimensions in GraphicsManager
            graphicsManager.setViewport(0, 0, SCREEN_WIDTH, SCREEN_HEIGHT);

            // Load ROM
            File romFile = ensureRomAvailable();
            if (romFile == null) {
                System.err.println("Sonic 2 ROM not available Ã¢â‚¬â€ visual regression tests will be skipped");
                initialized = false;
                return;
            }
            rom = new Rom();
            assertTrue(rom.open(romFile.getAbsolutePath()), "Failed to open ROM");

            // Register game module
            GameModuleRegistry.detectAndSetModule(rom);

            // Create player sprite (required by LevelManager.loadZoneAndAct)
            SonicConfigurationService configService = SonicConfigurationService.getInstance();
            String mainCode = configService.getString(SonicConfiguration.MAIN_CHARACTER_CODE);
            AbstractPlayableSprite mainSprite = new Sonic(mainCode, (short) 100, (short) 624);
            GameServices.sprites().addSprite(mainSprite);

            // Set up camera to follow player
            Camera camera = GameServices.camera();
            camera.setFocusedSprite(mainSprite);
            camera.updatePosition(true);

            initialized = true;

        } catch (Exception e) {
            // Initialization failed, tests will be skipped
            System.err.println("Visual regression test initialization failed: " + e.getMessage());
            e.printStackTrace();
            initialized = false;
        }
    }

    @AfterAll
    public static void tearDownClass() {
        // Restore debug view setting
        SonicConfigurationService.getInstance()
                .setConfigValue(SonicConfiguration.DEBUG_VIEW_ENABLED, originalDebugViewEnabled);

        if (window != NULL) {
            try {
                glfwDestroyWindow(window);
            } catch (Exception e) {
                // Ignore cleanup errors
            }
        }
        glfwTerminate();
        GraphicsManager.getInstance().resetState();
    }

    @Test
    public void testEhzAct1Checkpoint1() throws Exception {
        assumeTrue(initialized, "Test environment not initialized");
        assumeTrue(referenceFilesExist, "Reference files not generated yet. Run VisualReferenceGenerator first.");
        assertScreenshotMatchesReference(0, 0, 3568, 170, "ehz_a1_cp1.png");
    }

    @Test
    public void testEhzAct1Tunnel() throws Exception {
        assumeTrue(initialized, "Test environment not initialized");
        assumeTrue(referenceFilesExist, "Reference files not generated yet. Run VisualReferenceGenerator first.");
        // EHZ tunnel tests the priority rendering system (tunnel renders in front of Sonic)
        assertScreenshotMatchesReference(0, 0, 1806, 697, "ehz_a1_tunnel.png");
    }

    @Test
    public void testEhzAct2Checkpoint1() throws Exception {
        assumeTrue(initialized, "Test environment not initialized");
        assumeTrue(referenceFilesExist, "Reference files not generated yet. Run VisualReferenceGenerator first.");
        assertScreenshotMatchesReference(0, 1, 4224, 200, "ehz_a2_cp1.png");
    }

    @Test
    public void testCpzAct1Checkpoint1() throws Exception {
        assumeTrue(initialized, "Test environment not initialized");
        assumeTrue(referenceFilesExist, "Reference files not generated yet. Run VisualReferenceGenerator first.");
        assertScreenshotMatchesReference(1, 0, 4272, 1512, "cpz_a1_cp1.png");
    }

    @Test
    public void testCpzAct2Checkpoint1() throws Exception {
        assumeTrue(initialized, "Test environment not initialized");
        assumeTrue(referenceFilesExist, "Reference files not generated yet. Run VisualReferenceGenerator first.");
        assertScreenshotMatchesReference(1, 1, 3136, 616, "cpz_a2_cp1.png");
    }

    @Test
    public void testCnzAct1Checkpoint1() throws Exception {
        assumeTrue(initialized, "Test environment not initialized");
        assumeTrue(referenceFilesExist, "Reference files not generated yet. Run VisualReferenceGenerator first.");
        assertScreenshotMatchesReference(3, 0, 5944, 296, "cnz_a1_cp1.png");
    }

    @Test
    public void testHtzAct1Checkpoint1() throws Exception {
        assumeTrue(initialized, "Test environment not initialized");
        assumeTrue(referenceFilesExist, "Reference files not generated yet. Run VisualReferenceGenerator first.");
        // HTZ uses overlay tileset system - important to verify
        assertScreenshotMatchesReference(4, 0, 4160, 204, "htz_a1_cp1.png");
    }

    @Test
    public void testMczAct1Checkpoint1() throws Exception {
        assumeTrue(initialized, "Test environment not initialized");
        assumeTrue(referenceFilesExist, "Reference files not generated yet. Run VisualReferenceGenerator first.");
        assertScreenshotMatchesReference(5, 0, 1400, 1128, "mcz_a1_cp1.png");
    }

    /**
     * Render the level at the specified position and compare against reference image.
     * Uses checkpoint position for deterministic camera placement with visible objects.
     */
    private void assertScreenshotMatchesReference(int zone, int act, int playerX, int playerY, String filename)
            throws Exception {

        assumeTrue(referenceFileExists(filename), "Reference file not found: " + filename);

        // Load reference image
        RgbaImage reference = loadReferenceImage(filename);
        assertNotNull(reference, "Reference image should load: " + filename);

        // Render current output
        RgbaImage current = renderScreenshot(zone, act, playerX, playerY);

        // Compare images
        ScreenshotCapture.ComparisonResult result = ScreenshotCapture.imagesMatch(reference, current, PIXEL_TOLERANCE);

        if (!result.matched()) {
            // Save diff image for debugging
            saveDiffImage(filename, reference, current);

            fail(String.format(
                    "Visual mismatch for %s: %d pixels differ (max diff=%d), first diff at (%d, %d). " +
                    "Diff image saved to target/visual-diff/",
                    filename, result.diffCount(), result.maxDiff(), result.firstDiffX(), result.firstDiffY()
            ));
        }

        System.out.println("Visual match verified for " + filename);
    }

    /**
     * Render a screenshot of the level at the specified player position.
     */
    private RgbaImage renderScreenshot(int zone, int act, int playerX, int playerY) throws IOException {
        LevelManager levelManager = GameServices.level();
        Camera camera = GameServices.camera();
        GraphicsManager graphicsManager = GraphicsManager.getInstance();
        SpriteManager spriteManager = GameServices.sprites();

        // Clear all sprites to avoid state pollution from other tests
        // (other tests may leave mock sprites with empty sensor arrays)
        spriteManager.clearAllSprites();

        // Reset parallax state to ensure deterministic rendering
        // (forces HTZ cloudCounter to reset, etc.)
        GameServices.parallax().resetZoneState();

        // Create a fresh player sprite
        SonicConfigurationService configService = SonicConfigurationService.getInstance();
        String mainCode = configService.getString(SonicConfiguration.MAIN_CHARACTER_CODE);
        AbstractPlayableSprite player = new Sonic(mainCode, (short) playerX, (short) playerY);
        spriteManager.addSprite(player);
        camera.setFocusedSprite(player);

        // Load level
        levelManager.loadZoneAndAct(zone, act);

        // Move player to checkpoint position
        player.setX((short) playerX);
        player.setY((short) playerY);

        // Force camera to snap to player position (no smooth scrolling)
        camera.updatePosition(true);

        // Spawn objects within camera view
        levelManager.updateObjectPositions();

        // Update ring spawning within camera view
        if (levelManager.getRingManager() != null) {
            levelManager.getRingManager().update(camera.getX(), player, 0);
        }

        // Update sprite animation to set correct mapping frame
        // (default frame 0 is intentionally empty; WAIT animation starts at frame 15)
        GameServices.sprites().updateWithoutInput();

        // Clear screen with level's background color
        levelManager.setClearColor();
        glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);

        // Render level with sprites
        levelManager.drawWithSpritePriority(GameServices.sprites());

        // Flush all queued commands
        graphicsManager.flush();

        // Ensure all GL commands are complete
        glFinish();

        // Capture framebuffer
        return ScreenshotCapture.captureFramebuffer(SCREEN_WIDTH, SCREEN_HEIGHT);
    }

    /**
     * Save a diff image showing the differences between reference and current.
     */
    private void saveDiffImage(String originalFilename, RgbaImage reference, RgbaImage current)
            throws IOException {
        Path diffDir = TestSessionOutputPaths.diagnostics("visual-diff");
        Files.createDirectories(diffDir);

        // Save current image
        String currentFilename = originalFilename.replace(".png", "_current.png");
        Path currentPath = diffDir.resolve(currentFilename);
        ScreenshotCapture.savePNG(current, currentPath);

        // Save diff image
        RgbaImage diff = ScreenshotCapture.createDiffImage(reference, current, PIXEL_TOLERANCE);
        String diffFilename = originalFilename.replace(".png", "_diff.png");
        Path diffPath = diffDir.resolve(diffFilename);
        ScreenshotCapture.savePNG(diff, diffPath);

        System.out.println("Saved diff images to: " + diffDir.toAbsolutePath());
    }

    /**
     * Check if a reference file exists.
     */
    private static boolean referenceFileExists(String filename) {
        try (InputStream is = VisualRegressionTest.class.getClassLoader()
                .getResourceAsStream(REFERENCE_DIR + "/" + filename)) {
            return is != null;
        } catch (IOException e) {
            return false;
        }
    }

    /**
     * Load a reference image from resources.
     */
    private RgbaImage loadReferenceImage(String filename) throws IOException {
        // Try loading from classpath first
        try (InputStream is = getClass().getClassLoader()
                .getResourceAsStream(REFERENCE_DIR + "/" + filename)) {
            if (is == null) {
                // Fall back to file system
                Path filePath = Paths.get("src/test/resources", REFERENCE_DIR, filename);
                if (!Files.exists(filePath)) {
                    return null;
                }
                return ScreenshotCapture.loadPNG(filePath);
            }

            // Copy to temp file for ImageIO (works better with streams)
            File tempFile = File.createTempFile("visual_ref_", ".png");
            tempFile.deleteOnExit();
            Files.copy(is, tempFile.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
            return ScreenshotCapture.loadPNG(tempFile.toPath());
        }
    }
}

