package uk.co.jamesj999.sonic.game.sonic2.objects;

import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Generated from docs/SPGSonic2Overlay.Lua for built-in object name coverage.
 */
public final class Sonic2ObjectRegistryData {
    private Sonic2ObjectRegistryData() {
    }

    public static final Map<Integer, List<String>> NAMES_BY_ID = build();

    private static Map<Integer, List<String>> build() {
        Map<Integer, List<String>> map = new HashMap<>();
        map.put(0x01, List.of("Sonic"));
        map.put(0x02, List.of("Tails"));
        map.put(0x03, List.of("LayerSwitcher"));
        map.put(0x04, List.of("WaterSurface"));
        map.put(0x05, List.of("TailsTails"));
        map.put(0x06, List.of("Spiral"));
        map.put(0x07, List.of("Oil"));
        map.put(0x08, List.of("SpindashDust", "Splash"));
        map.put(0x09, List.of("SonicSS"));
        map.put(0x0A, List.of("SmallBubbles"));
        map.put(0x0B, List.of("TippingFloor"));
        map.put(0x0D, List.of("GoalPlate"));
        map.put(0x0E, List.of("IntroStars"));
        map.put(0x0F, List.of("TitleMenu"));
        map.put(0x10, List.of("TailsSS"));
        map.put(0x11, List.of("Bridge"));
        map.put(0x12, List.of("HPZEmerald"));
        map.put(0x13, List.of("HPZWaterfall"));
        map.put(0x14, List.of("Seesaw"));
        map.put(0x15, List.of("SwingingPlatform"));
        map.put(0x16, List.of("HTZLift"));
        map.put(0x18, List.of("ARZPlatform", "EHZPlatform"));
        map.put(0x19, List.of("CPZPlatform", "OOZMovingPform", "WFZPlatform"));
        map.put(0x1A, List.of("HPZCollapsPform"));
        map.put(0x1B, List.of("SpeedBooster"));
        map.put(0x1C, List.of("Scenery", "BridgeStake", "Stump/FallingOil"));
        map.put(0x1D, List.of("BlueBalls"));
        map.put(0x1E, List.of("CPZSpinTube"));
        map.put(0x1F, List.of("CollapsPform"));
        map.put(0x20, List.of("LavaBubble"));
        map.put(0x21, List.of("HUD"));
        map.put(0x22, List.of("ArrowShooter"));
        map.put(0x23, List.of("FallingPillar"));
        map.put(0x24, List.of("Bubbles"));
        map.put(0x25, List.of("Ring"));
        map.put(0x26, List.of("Monitor"));
        map.put(0x27, List.of("Explosion"));
        map.put(0x28, List.of("Animal"));
        map.put(0x29, List.of("Points"));
        map.put(0x2A, List.of("Stomper"));
        map.put(0x2B, List.of("RisingPillar"));
        map.put(0x2C, List.of("LeavesGenerator"));
        map.put(0x2D, List.of("Barrier"));
        map.put(0x2E, List.of("MonitorContents"));
        map.put(0x2F, List.of("SmashableGround"));
        map.put(0x30, List.of("RisingLava"));
        map.put(0x31, List.of("LavaMarker"));
        map.put(0x32, List.of("BreakableBlock", "BreakableRock"));
        map.put(0x33, List.of("OOZPoppingPform"));
        map.put(0x34, List.of("TitleCard"));
        map.put(0x35, List.of("InvStars"));
        map.put(0x36, List.of("Spikes"));
        map.put(0x37, List.of("LostRings"));
        map.put(0x38, List.of("Shield"));
        map.put(0x39, List.of("GameOver", "TimeOver"));
        map.put(0x3A, List.of("Results"));
        map.put(0x3D, List.of("OOZLauncher"));
        map.put(0x3E, List.of("EggPrison"));
        map.put(0x3F, List.of("Fan"));
        map.put(0x40, List.of("Springboard"));
        map.put(0x41, List.of("Spring"));
        map.put(0x42, List.of("SteamSpring"));
        map.put(0x43, List.of("SlidingSpike"));
        map.put(0x44, List.of("Bumper"));
        map.put(0x45, List.of("OOZSpring"));
        map.put(0x46, List.of("OOZBall"));
        map.put(0x47, List.of("Button"));
        map.put(0x48, List.of("LauncherBall"));
        map.put(0x49, List.of("EHZWaterfall"));
        map.put(0x4A, List.of("Octus"));
        map.put(0x4B, List.of("Buzzer"));
        map.put(0x50, List.of("Aquis"));
        map.put(0x51, List.of("CNZBoss"));
        map.put(0x52, List.of("HTZBoss"));
        map.put(0x53, List.of("MTZBossOrb"));
        map.put(0x54, List.of("MTZBoss"));
        map.put(0x55, List.of("OOZBoss"));
        map.put(0x56, List.of("EHZBoss"));
        map.put(0x57, List.of("MCZBoss"));
        map.put(0x58, List.of("BossExplosion"));
        map.put(0x59, List.of("SSEmerald"));
        map.put(0x5A, List.of("SSMessage"));
        map.put(0x5B, List.of("SSRingSpill"));
        map.put(0x5C, List.of("Masher"));
        map.put(0x5D, List.of("CPZBoss"));
        map.put(0x5E, List.of("SSHUD"));
        map.put(0x5F, List.of("StartBanner", "EndingController"));
        map.put(0x60, List.of("SSRing"));
        map.put(0x61, List.of("SSBomb"));
        map.put(0x63, List.of("SSShadow"));
        map.put(0x64, List.of("MTZTwinStompers"));
        map.put(0x65, List.of("MTZLongPlatform"));
        map.put(0x66, List.of("MTZSpringWall"));
        map.put(0x67, List.of("MTZSpinTube"));
        map.put(0x68, List.of("SpikyBlock"));
        map.put(0x69, List.of("Nut"));
        map.put(0x6A, List.of("MCZRotPforms", "MTZMovingPforms"));
        map.put(0x6B, List.of("MTZPlatform", "CPZSquarePform"));
        map.put(0x6C, List.of("Conveyor"));
        map.put(0x6D, List.of("FloorSpike"));
        map.put(0x6E, List.of("LargeRotPform"));
        map.put(0x6F, List.of("SSResults"));
        map.put(0x70, List.of("Cog"));
        map.put(0x71, List.of("MTZLavaBubble", "HPZBridgeStake", "PulsingOrb"));
        map.put(0x72, List.of("CNZConveyorBelt"));
        map.put(0x73, List.of("RotatingRings"));
        map.put(0x74, List.of("InvisibleBlock"));
        map.put(0x75, List.of("MCZBrick"));
        map.put(0x76, List.of("SlidingSpikes"));
        map.put(0x77, List.of("MCZBridge"));
        map.put(0x78, List.of("CPZStaircase"));
        map.put(0x79, List.of("Checkpoint"));
        map.put(0x7A, List.of("SidewaysPform"));
        map.put(0x7B, List.of("PipeExitSpring"));
        map.put(0x7C, List.of("CPZPylon"));
        map.put(0x7E, List.of("SuperSonicStars"));
        map.put(0x7F, List.of("VineSwitch"));
        map.put(0x80, List.of("MovingVine"));
        map.put(0x81, List.of("MCZDrawbridge"));
        map.put(0x82, List.of("SwingingPform"));
        map.put(0x83, List.of("ARZRotPforms"));
        map.put(0x84, List.of("ForcedSpin", "PinballMode"));
        map.put(0x85, List.of("LauncherSpring"));
        map.put(0x86, List.of("Flipper"));
        map.put(0x87, List.of("SSNumberOfRings"));
        map.put(0x88, List.of("SSTailsTails"));
        map.put(0x89, List.of("ARZBoss"));
        map.put(0x8B, List.of("WFZPalSwitcher"));
        map.put(0x8C, List.of("Whisp"));
        map.put(0x8D, List.of("GrounderInWall"));
        map.put(0x8E, List.of("GrounderInWall2"));
        map.put(0x8F, List.of("GrounderWall"));
        map.put(0x90, List.of("GrounderRocks"));
        map.put(0x91, List.of("ChopChop"));
        map.put(0x92, List.of("Spiker"));
        map.put(0x93, List.of("SpikerDrill"));
        map.put(0x94, List.of("Rexon"));
        map.put(0x95, List.of("Sol"));
        map.put(0x96, List.of("Rexon2"));
        map.put(0x97, List.of("RexonHead"));
        map.put(0x98, List.of("Projectile"));
        map.put(0x99, List.of("Nebula"));
        map.put(0x9A, List.of("Turtloid"));
        map.put(0x9B, List.of("TurtloidRider"));
        map.put(0x9C, List.of("BalkiryJet"));
        map.put(0x9D, List.of("Coconuts"));
        map.put(0x9E, List.of("Crawlton"));
        map.put(0x9F, List.of("Shellcracker"));
        map.put(0xA0, List.of("ShellcrackerClaw"));
        map.put(0xA1, List.of("Slicer"));
        map.put(0xA2, List.of("SlicerPincers"));
        map.put(0xA3, List.of("Flasher"));
        map.put(0xA4, List.of("Asteron"));
        map.put(0xA5, List.of("Spiny"));
        map.put(0xA6, List.of("SpinyOnWall"));
        map.put(0xA7, List.of("Grabber"));
        map.put(0xA8, List.of("GrabberLegs"));
        map.put(0xA9, List.of("GrabberBox"));
        map.put(0xAA, List.of("GrabberString"));
        map.put(0xAC, List.of("Balkiry"));
        map.put(0xAD, List.of("CluckerBase"));
        map.put(0xAE, List.of("Clucker"));
        map.put(0xAF, List.of("MechaSonic"));
        map.put(0xB0, List.of("SonicOnSegaScr"));
        map.put(0xB1, List.of("SegaHideTM"));
        map.put(0xB2, List.of("Tornado"));
        map.put(0xB3, List.of("Cloud"));
        map.put(0xB4, List.of("VPropeller"));
        map.put(0xB5, List.of("HPropeller"));
        map.put(0xB6, List.of("TiltingPlatform"));
        map.put(0xB7, List.of("VerticalLaser"));
        map.put(0xB8, List.of("WallTurret"));
        map.put(0xB9, List.of("Laser"));
        map.put(0xBA, List.of("WFZWheel"));
        map.put(0xBC, List.of("WFZShipFire"));
        map.put(0xBD, List.of("SmallMetalPform"));
        map.put(0xBE, List.of("LateralCannon"));
        map.put(0xBF, List.of("WFZStick"));
        map.put(0xC0, List.of("SpeedLauncher"));
        map.put(0xC1, List.of("BreakablePlating"));
        map.put(0xC2, List.of("Rivet"));
        map.put(0xC3, List.of("TornadoSmoke"));
        map.put(0xC4, List.of("TornadoSmoke2"));
        map.put(0xC5, List.of("WFZBoss"));
        map.put(0xC6, List.of("Eggman"));
        map.put(0xC7, List.of("Eggrobo"));
        map.put(0xC8, List.of("Crawl"));
        map.put(0xC9, List.of("TtlScrPalChanger"));
        map.put(0xCA, List.of("CutScene"));
        map.put(0xCB, List.of("EndingSeqClouds"));
        map.put(0xCC, List.of("EndingSeqTrigger"));
        map.put(0xCD, List.of("EndingSeqBird"));
        map.put(0xCE, List.of("EndingSeqSonic", "EndingSeqTails"));
        map.put(0xCF, List.of("TornadoHelixes"));
        map.put(0xD2, List.of("CNZRectBlocks"));
        map.put(0xD3, List.of("BombPrize"));
        map.put(0xD4, List.of("CNZBigBlock"));
        map.put(0xD5, List.of("Elevator"));
        map.put(0xD6, List.of("PointPokey"));
        map.put(0xD7, List.of("HexBumper"));
        map.put(0xD8, List.of("BonusBlock"));
        map.put(0xD9, List.of("Grab"));
        map.put(0xDA, List.of("ContinueText", "ContinueIcons"));
        map.put(0xDB, List.of("ContinueChars"));
        map.put(0xDC, List.of("RingPrize"));
        return Collections.unmodifiableMap(map);
    }
}
