package com.openggf.game.rewind.snapshot;

import java.util.AbstractMap;
import java.util.AbstractSet;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import java.util.function.BiFunction;
import java.util.function.Function;

/**
 * Snapshot of {@link com.openggf.game.animation.AnimatedTileChannelGraph} per-frame state.
 * Captures the last-resolved phase per channel so rewind round-trips animated
 * tile animation state. The channels list itself is set at zone load and treated
 * as immutable for rewind; pattern bytes are derived state regenerated by the
 * animator counters (Track E) and are excluded.
 */
public record AnimatedTileChannelSnapshot(Map<String, Integer> lastPhaseByChannel) {
    private static final long PRESENT = 1L << 32;

    public AnimatedTileChannelSnapshot {
        Objects.requireNonNull(lastPhaseByChannel, "lastPhaseByChannel");
        if (!(lastPhaseByChannel instanceof CompactPhaseMap)) {
            lastPhaseByChannel = Map.copyOf(lastPhaseByChannel);
        }
    }

    /** Creates a production snapshot that owns a presence-tagged primitive payload. */
    public static AnimatedTileChannelSnapshot compact(Layout layout,
                                                      int[] phases,
                                                      boolean[] present,
                                                      int presentCount) {
        Objects.requireNonNull(layout, "layout");
        Objects.requireNonNull(phases, "phases");
        Objects.requireNonNull(present, "present");
        if (phases.length != layout.size() || present.length != layout.size()) {
            throw new IllegalArgumentException("Phase arrays must match snapshot layout size");
        }
        if (presentCount < 0 || presentCount > layout.size()) {
            throw new IllegalArgumentException("Invalid present phase count: " + presentCount);
        }
        if (layout.hasNullKey()) {
            throw new NullPointerException("Animated tile snapshot key");
        }
        long[] slots = new long[layout.size()];
        int actualPresentCount = 0;
        for (int index = 0; index < slots.length; index++) {
            if (present[index]) {
                slots[index] = PRESENT | Integer.toUnsignedLong(phases[index]);
                actualPresentCount++;
            }
        }
        if (actualPresentCount != presentCount) {
            throw new IllegalArgumentException(
                    "Present phase count " + presentCount + " does not match payload " + actualPresentCount);
        }
        return new AnimatedTileChannelSnapshot(new CompactPhaseMap(layout, slots, presentCount));
    }

    /**
     * Copies a compact payload directly when it shares the graph's exact layout.
     * Returns the present count, or {@code -1} when a keyed restore is required.
     */
    public int copyCompactState(Layout expectedLayout, int[] phases, boolean[] present) {
        if (!(lastPhaseByChannel instanceof CompactPhaseMap compact)
                || compact.layout != expectedLayout) {
            return -1;
        }
        if (phases.length != compact.slots.length || present.length != compact.slots.length) {
            throw new IllegalArgumentException("Restore arrays must match compact snapshot layout");
        }
        for (int index = 0; index < compact.slots.length; index++) {
            long slot = compact.slots[index];
            boolean isPresent = (slot & PRESENT) != 0;
            present[index] = isPresent;
            if (isPresent) {
                phases[index] = (int) slot;
            }
        }
        return compact.presentCount;
    }

    boolean isCompact() {
        return lastPhaseByChannel instanceof CompactPhaseMap;
    }

    boolean sharesLayoutWith(AnimatedTileChannelSnapshot other) {
        return lastPhaseByChannel instanceof CompactPhaseMap left
                && Objects.requireNonNull(other, "other").lastPhaseByChannel instanceof CompactPhaseMap right
                && left.layout == right.layout;
    }

    boolean sharesPayloadWith(AnimatedTileChannelSnapshot other) {
        return lastPhaseByChannel instanceof CompactPhaseMap left
                && Objects.requireNonNull(other, "other").lastPhaseByChannel instanceof CompactPhaseMap right
                && left.slots == right.slots;
    }

    /** Returns the compact payload length, or {@code -1} for an external map snapshot. */
    public int compactPayloadLength() {
        return lastPhaseByChannel instanceof CompactPhaseMap compact ? compact.slots.length : -1;
    }

    /** Returns the immutable compact layout, or {@code null} for an external map snapshot. */
    public Layout compactLayoutOrNull() {
        return lastPhaseByChannel instanceof CompactPhaseMap compact ? compact.layout : null;
    }

    /** Immutable key layout owned by one graph installation/diagnostic generation. */
    public static final class Layout {
        private final String[] keys;
        private final Map<String, Integer> indexByKey;
        private final boolean hasNullKey;

        private Layout(String[] keys) {
            this.keys = keys;
            this.indexByKey = new HashMap<>(hashCapacity(keys.length));
            boolean foundNull = false;
            for (int index = 0; index < keys.length; index++) {
                String key = keys[index];
                foundNull |= key == null;
                if (indexByKey.put(key, index) != null) {
                    throw new IllegalArgumentException("Duplicate animated tile snapshot key: " + key);
                }
            }
            hasNullKey = foundNull;
        }

        public static Layout fromKeys(List<String> keys) {
            Objects.requireNonNull(keys, "keys");
            return new Layout(keys.toArray(String[]::new));
        }

        public Layout append(String key) {
            if (indexByKey.containsKey(key)) {
                return this;
            }
            String[] appended = Arrays.copyOf(keys, keys.length + 1);
            appended[keys.length] = key;
            return new Layout(appended);
        }

        public int size() {
            return keys.length;
        }

        public String keyAt(int index) {
            return keys[index];
        }

        public int indexOf(Object key) {
            Integer index = indexByKey.get(key);
            return index == null ? -1 : index;
        }

        private boolean hasNullKey() {
            return hasNullKey;
        }

        private static int hashCapacity(int entryCount) {
            return entryCount < 3 ? entryCount + 1 : (int) Math.ceil(entryCount / 0.75d);
        }
    }

    private static final class CompactPhaseMap extends AbstractMap<String, Integer> {
        private final Layout layout;
        private final long[] slots;
        private final int presentCount;

        private CompactPhaseMap(Layout layout, long[] slots, int presentCount) {
            this.layout = layout;
            this.slots = slots;
            this.presentCount = presentCount;
        }

        @Override
        public int size() {
            return presentCount;
        }

        @Override
        public boolean containsKey(Object key) {
            Objects.requireNonNull(key, "key");
            int index = layout.indexOf(key);
            return index >= 0 && (slots[index] & PRESENT) != 0;
        }

        @Override
        public Integer get(Object key) {
            Objects.requireNonNull(key, "key");
            int index = layout.indexOf(key);
            return index >= 0 && (slots[index] & PRESENT) != 0 ? (int) slots[index] : null;
        }

        @Override
        public boolean containsValue(Object value) {
            Objects.requireNonNull(value, "value");
            if (!(value instanceof Integer integer)) {
                return false;
            }
            int expected = integer;
            for (long slot : slots) {
                if ((slot & PRESENT) != 0 && (int) slot == expected) {
                    return true;
                }
            }
            return false;
        }

        @Override
        public Set<Entry<String, Integer>> entrySet() {
            return Collections.unmodifiableSet(new AbstractSet<>() {
                @Override
                public int size() {
                    return presentCount;
                }

                @Override
                public Iterator<Entry<String, Integer>> iterator() {
                    return new Iterator<>() {
                        private int nextIndex = findNext(0);

                        @Override
                        public boolean hasNext() {
                            return nextIndex < slots.length;
                        }

                        @Override
                        public Entry<String, Integer> next() {
                            if (!hasNext()) {
                                throw new NoSuchElementException();
                            }
                            int current = nextIndex;
                            nextIndex = findNext(current + 1);
                            return new SimpleImmutableEntry<>(layout.keyAt(current), (int) slots[current]);
                        }

                        private int findNext(int start) {
                            int index = start;
                            while (index < slots.length && (slots[index] & PRESENT) == 0) {
                                index++;
                            }
                            return index;
                        }
                    };
                }

            });
        }

        @Override
        public Set<String> keySet() {
            return Collections.unmodifiableSet(super.keySet());
        }

        @Override
        public Collection<Integer> values() {
            return Collections.unmodifiableCollection(super.values());
        }

        @Override public Integer put(String key, Integer value) { throw immutable(); }
        @Override public Integer remove(Object key) { throw immutable(); }
        @Override public void putAll(Map<? extends String, ? extends Integer> map) { throw immutable(); }
        @Override public void clear() { throw immutable(); }
        @Override public Integer putIfAbsent(String key, Integer value) { throw immutable(); }
        @Override public boolean remove(Object key, Object value) { throw immutable(); }
        @Override public boolean replace(String key, Integer oldValue, Integer newValue) { throw immutable(); }
        @Override public Integer replace(String key, Integer value) { throw immutable(); }
        @Override public void replaceAll(BiFunction<? super String, ? super Integer, ? extends Integer> function) {
            throw immutable();
        }
        @Override public Integer computeIfAbsent(String key,
                Function<? super String, ? extends Integer> function) { throw immutable(); }
        @Override public Integer computeIfPresent(String key,
                BiFunction<? super String, ? super Integer, ? extends Integer> function) { throw immutable(); }
        @Override public Integer compute(String key,
                BiFunction<? super String, ? super Integer, ? extends Integer> function) { throw immutable(); }
        @Override public Integer merge(String key, Integer value,
                BiFunction<? super Integer, ? super Integer, ? extends Integer> function) { throw immutable(); }

        private static UnsupportedOperationException immutable() {
            return new UnsupportedOperationException("immutable snapshot map");
        }
    }
}
